cart2/urls.py
from django.urls import path
from . import views

app_name = 'cart2'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('cart_clear/', views.cart_clear, name='cart_clear'),
]

fastfood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),    
    path('cart/', include('cart2.urls')),
    path('accounts/', include('allauth.urls')),
    path('acounts/', include('accounts.urls')), 

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *
from . import views
from django.contrib.auth import views as auth_views
from allauth.account.views import LoginView, SignupView 


app_name = 'website'


urlpatterns = [
    path('', index_view, name = 'index'), 
    path('menu.html', menu_view, name = 'menu'), 
    path('about', about_view, name = 'about'),
    path('index.html', contact_view, name = 'contact'), 
    
    path('login', login_view, name='login' ),

    # path('to-bank/', views.to_bank, name='to_bank'),
    path('order_details', views.callback, name='order_details'),
    
    path('order_details2', order_details_view, name='order_details2'),
]

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Navbar -->
<div class="container-xxl position-relative p-0">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
        <a href="{% url 'website:index' %}" class="navbar-brand p-0">
            <h1 style="color: whitesmoke;"><i class="text-primary m-0">紅龍 </i>اژدهای سرخ</h1>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="fa fa-bars"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0 pe-4">
                <a href="{% url 'website:index' %}" class="nav-item nav-link">صفحه اصلی</a>
                <a href="{% url 'website:about' %}" class="nav-item nav-link active">درباره ما</a>
                <a href="{% url 'website:menu' %}" class="nav-item nav-link">منوی غذا</a>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'account_logout' %}" class="nav-item nav-link">خروج از حساب کاربری</a>
                    <a href="{% url 'profile' %}" class="nav-item nav-link">پروفایل کاربری</a>
                {% else %}
                    <a href="{% url 'website:login' %}" class="nav-item nav-link">ورود / ثبت نام</a>
                {% endif %}
                <a href="{% url 'website:order_details2' %}" class="nav-item nav-link">جزئیات خرید</a>
            </div>
        </div>
    </nav>
</div>

<div class="container-xxl py-5 bg-dark hero-header mb-5">
    <div class="container text-center my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown"> درباره ما</h1>
    </div>
</div>

{% include 'about_content.html' %}

{% endblock %}

templates/about_content.html
{% load static %}
{% block content %}

<!-- About  -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-5 align-items-center">
            <div class="col-lg-6">
                <div class="row g-3">
                    <div class="col-6 text-start">
                        <img class="img-fluid rounded w-100 wow zoomIn" data-wow-delay="0.1s"
                            src="{% static '/img/restaurant(2).jpg' %}">
                    </div>
                    <div class="col-6 text-start">
                        <img class="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.3s"
                            src="{% static '/img/restaurant(4).jpg' %}" style="margin-top: 25%;">
                    </div>
                    <div class="col-6 text-end">
                        <img class="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.5s"
                            src="{% static '/img/restaurant(4).jpg' %}">
                    </div>
                    <div class="col-6 text-end">
                        <img class="img-fluid rounded w-100 wow zoomIn" data-wow-delay="0.7s"
                            src="{% static '/img/restaurant(2).jpg' %}">
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <h1 class="mb-4"> مجموعه اژدهای سرخ </h1>
                <div class="row g-4 mb-4">
                    <div class="col-sm-6">
                        <div class="d-flex align-items-center border-start border-5 border-primary px-3">
                            <h1 class="flex-shrink-0 display-5 text-primary mb-0" data-toggle="counter-up">3</h1>
                            <div class="ps-4 ">
                                <p class="mb-0" style="margin-right: 40%;">سال</p>
                                <h6 class="text-uppercase mb-0" style="margin-right: 40%;">تجربه</h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="d-flex align-items-center border-start border-5 border-primary px-3">
                            <h1 class="flex-shrink-0 display-5 text-primary mb-0" data-toggle="counter-up">20</h1>
                            <div class="ps-4">
                                <p class="mb-0">نوع</p>
                                <h6 class="text-uppercase mb-0">غذای متنوع</h6>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- About -->

{% endblock %}

templates/base.html
{% load static %}
{% load account %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    <meta charset="utf-8">
    <title>درباره ما</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static '/img/tab-logo.png' %}" rel="icon">

    <!--  Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&family=Pacifico&display=swap"
        rel="stylesheet">

    <!-- Icon Font  -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries  -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!--  Bootstrap  -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- css -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-xxl bg-white p-0">
        <!-- Spinner  -->
        <div id="spinner"
            class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner  -->

        <!-- Navbar -->
        <div class="container-xxl position-relative p-0">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
                <a href="{% url 'website:index' %}" class="navbar-brand p-0">
                    <h1 style="color: whitesmoke;"><i class="text-primary m-0">紅龍 </i>اژدهای سرخ</h1>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto py-0 pe-4">
                        <a href="{% url 'website:index' %}" class="nav-item nav-link active">صفحه اصلی</a>
                        <a href="{% url 'website:about' %}" class="nav-item nav-link">درباره ما</a>
                        <a href="{% url 'website:menu' %}" class="nav-item nav-link ">منوی غذا </a>
                        {% if request.user.is_authenticated %}
                        
                        <a href="{% url 'account_logout' %}" class="nav-item nav-link">خروج از حساب کاربری</a>
                        <a href="{% url 'profile' %}" class="nav-item nav-link">پروفایل کاربری</a>
                        
                        {% else %}
                        <a href="{% url 'website:login' %}"  class="nav-item nav-link">ورود / ثبت نام</a>
                        
                        {% endif %}
                        <a href="{% url 'website:order_details2' %}"  class="nav-item nav-link">جزئیات خرید</a>
                    </div>
                </div>
                <!--cart-->
                <div id="cart-info" class="icons cart-info">
                    {% with total_items=cart|length %}

                    <a href="{% url 'cart2:cart_detail' %}" class="btn btn-primary py-2 px-4">
                        <p class="mb-0 text-capitalize">
                            <div class="fas fa-shopping-cart" id="cart-btn"></div>
                            <span id="item-count"> {{ total_items }} </span>
                        </p>
                    </a>
                    {% endwith %}
                </div>
                <div id="cart" class="cart" dir="ltr">



                    <!-- cart item -->

                    {% with total_items=cart|length %}
                    {% if total_items > 0 %}

                    <div class="cart-total-container d-flex justify-content-around text-capitalize mt-5" dir="ltr">
                        <h5>مجموع</h5>
                        <h5 dir="lt"> <strong id="cart-total" class="font-weight-bold">
                                {{ cart.get_total_price|floatformat:"0" }}

                            </strong> تومان</h5>
                    </div>
                    <div class="cart-buttons-container mt-3 d-flex justify-content-between">
                        <a href="{% url 'cart2:cart_clear' %}" id="clear-cart"
                            class="btn btn-outline-secondary btn-black text-uppercase">پاک کردن همه</a>


                            <!-- url 'website:to_bank -->
                            <form action="" method="post">
                                {% csrf_token %}
                            <input type="submit" value="ثبت سفارش" class="btn btn-outline-secondary text-uppercase btn-pink">
                            </form>
                    </div>

                    {% else %}
                    <p> هنوز چیزی انتخاب نکرده‌اید</p>

                    {% endif %}
                    {% endwith %}
            </nav>
        </div>

        <!-- Navbar -->

        {% block content %}
        {% endblock %}



        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-lg-3 col-md-6">
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">ارتباط با ما</h4>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"> </i> کرمان، خیابان فیروزه، نبش کوچه5</p>
                        <a href="tel:03432454513" class="mb-2" dir="ltr" style="color: #fff;"> 034 3245 4513 <i
                                class="fa fa-phone-alt me-3"></i></a>
                        <div class="d-flex pt-2">

                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">ساعت کاری</h4>
                        <h5 class="text-light fw-normal">شنبه تا پنجشنبه</h5>
                        <p>7 صبح تا 12 شب</p>

                    </div>
                    <div class="col-lg-3 col-md-6">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="#">Red Dragon</a>, All Right Reserved.
                            Designed By <a class="border-bottom"
                                href="https://github.com/red-dragon-front/front.git">print("Hello World!")</a>
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/cart_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .item_container {
        position: relative;
        padding: 0.5rem;
        -webkit-box-shadow: 0 2px 3px 0 rgba(125,125,125,0.5);
        box-shadow: 0 2px 3px 0 rgba(125,125,125,0.5);
        border: none;
        margin-bottom: 1rem;
        background: #fff;
        border-radius: 4px;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        overflow: hidden;
    }
    .item_CardContainer {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: horizontal;
        -webkit-box-direction: reverse;
        -ms-flex-direction: row-reverse;
        flex-direction: row-reverse;
        position: relative;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        direction: ltr;
    }
    .item_imageContainer {
        width: 105px;
        height: 105px;
        white-space: nowrap;
        border-radius: 5px;
    }
    .item_image {
        width: 100%;
        height: 100%;
        background-repeat: no-repeat;
        background-position: center center;
        background-size: 102%;
        border: 1px solid #d8d8d8;
        position: relative;
        border-radius: 5px;
    }
    .item_text {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-flex: 8;
        -ms-flex: 8;
        flex: 8;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        padding-right: 0.5rem;
        -webkit-box-pack: justify;
        -ms-flex-pack: justify;
        justify-content: space-between;
        text-align: right;
        padding-top: 0.5rem;
        direction: rtl;
        padding-left: 0.6em;
    }
    .item_text h4 {
        font-weight: 700;
        font-size: 1.5rem;
        direction: rtl;
        color: black;
    }
    .item_text p {
        font-size: 1.1rem;
        direction: rtl;
        margin-top: 0.5rem;
    }
    .item_price {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-pack: justify;
        -ms-flex-pack: justify;
        justify-content: space-between;
        -webkit-box-orient: horizontal;
        -webkit-box-direction: reverse;
        -ms-flex-direction: row-reverse;
        flex-direction: row-reverse;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
    }
</style>

<div class="container-xxl py-5 bg-dark hero-header mb-5">
    <div class="container text-center my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">سبد خرید</h1>
    </div>
</div>

<div class="container-xxl py-5">
    <div class="container">
        <div class="tab-class text-center wow ">
            <div class="tab-content">
                <div id="tab-1" class="tab-pane p-0 active">
                    <div class="row g-4">
                        <!-- Menu Start -->
                            <div class="row" class="store-items" id="store-items">
                                {% for item in cart %}
                                <div class="item_container animated slideInRight">
                                    <div class="item_CardContainer">
                                        <div class="item_imageContainer">
                                            <div class="item_image" style='background-image: url("{{ item.product.image.url }}");'></div>
                                        </div>
                                        <div class="item_text">
                                            <div>
                                                <h4>{{ item.product.name_farsi }}</h4>
                                                <p>{{ item.product.description }}</p>
                                                
                                            </div>
                                            <div class="item_price">
                                                <span class="price">{{ item.price|floatformat:"0" }}&nbsp;تومان</span>
                                                <a href="{% url 'cart2:cart_remove' item.product.id %}"><i class="fas fa-trash"></i>حذف</a>
                                            </div>
                                            <div class="item_price">
                                                <span class="price">تعداد محصول: {{ item.product_count }} عدد</span>
                                            </div>
                                            <div class="item_price">
                                                <span class="price">مجموع: {{ item.total_price }} تومان</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% empty %}
                                <h5 class="mb-5">
                                    غذا یا نوشیدنی در سبد خرید شما وجود ندارد.   
                                </h5>
                            {% endfor %}
                            
                            <h4>مجموع کل: {{ cart.get_total_price|floatformat:"0" }} تومان</h4>

                            {% if cart.get_total_price > 0 %}
                                <div class="cart-buttons-container mt-3 d-flex justify-content-between">
                                    <a href="{% url 'cart2:cart_clear' %}" id="clear-cart"
                                        class="btn btn-outline-secondary btn-black text-uppercase">پاک کردن همه</a>
                                        <form action="{% url 'website:order_details2' %}" method="post">
                                            {% csrf_token %}
                                        <input type="submit" value="ثبت سفارش" class="btn btn-outline-secondary text-uppercase btn-pink">
                                        </form>
                                </div>
                            {% endif %}
                
                        </div>
                        <!-- Menu End -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

templates/contact.html
{% load static %}
{% block content %}
<!-- Comments -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h5 class="  text-center text-primary fw-normal">با ما در ارتباط باشید</h5>
            <h1 class="mb-5">پذیرای نظرات و انتقادات شما هستیم</h1>
        </div>
        <div class="row g-4">
            <div class="col-md-6 wow fadeIn" data-wow-delay="0.1s">
                <iframe class="position-relative rounded w-100 h-100"
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3445.3837238748342!2d57.05020142469222!3d30.283135874804312!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3f0219cfc627c56f%3A0x69e533ed0cc487a0!2z2LHYs9iq2YjYsdin2YYg2obbjNmG24wg2KfamNiv2YfYp9uMINiz2LHYrg!5e0!3m2!1sfa!2s!4v1683825340389!5m2!1sfa!2s"
                    frameborder="0" style="min-height: 350px; border:0;" allowfullscreen="" aria-hidden="false"
                    tabindex="0"></iframe>
            </div>



            <div class="col-md-6">
                <div class="wow fadeInUp" data-wow-delay="0.2s">
                    <form action="{% url 'website:contact' %}" method="post">
                        
                        <div class="row g-3">
                            {% csrf_token %}

                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input name="name" type="text" class="form-control" id="comment-name"
                                        placeholder="comment-name">
                                    <label for="comment-name">نام</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input name="family_name" type="text" class="form-control" id="comment-last-name"
                                        placeholder="comment-last-name">
                                    <label for="comment-last-name">نام خانوادگی</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating">
                                    <input name="email" type="email" class="form-control" id="comment-email"
                                        placeholder="comment-email">
                                    <label for="comment-email">آدرس ایمیل</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating">
                                    <textarea name="message" class="form-control" placeholder="Leave a message here"
                                        id="message" style="height: 150px"></textarea>
                                    <label for="message">لطفا دیدگاه خود را وارد کنید</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <button class="btn btn-primary w-100 py-3" type="submit">ثبت دیدگاه</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container-xxl py-5 bg-dark hero-header mb-5">
    <div class="container my-5 py-5">
        <div class="row align-items-center g-5">
            <div class="col-lg-6 text-center text-lg-start">
                <h1 class="display-3 text-white animated slideInLeft">اولین مجموعه<br>غذاهای چینی در کرمان
                </h1>
                <p class="text-white animated slideInLeft mb-4 pb-2">طبخ انواع غذاهای چینی با ذائقه ایرانی
                </p>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'website:about' %}" clss="btn btn-primary py-sm-3 px-sm-5 me-3 animated slideInLeft">به مجموعه اژدهای سرخ خوش آمدید</a>
                {% else %}
                    <a href="{% url 'website:login' %}" class="btn btn-primary py-sm-3 px-sm-5 me-3 animated slideInLeft">ورود / ثبت نام</a>
                {% endif %}
            </div>
            <div class="col-lg-6 text-center text-lg-end overflow-hidden">
                <img class="img-fluid" src="{% static 'img/111.png' %}" alt="Loading...">
            </div>
        </div>
    </div>
</div>
</div>
<!-- Navbar -->

{% include 'about_content.html' %}



<!-- Menu  -->
{% include 'menu_content.html' %}
<!-- Menu End -->


{% include 'contact.html' %}


{% endblock %}

templates/menu.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Navbar -->
<div class="container-xxl position-relative p-0">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
        <a href="{% url 'website:index' %}" class="navbar-brand p-0">
            <h1 style="color: whitesmoke;"><i class="text-primary m-0">紅龍 </i>اژدهای سرخ</h1>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="fa fa-bars"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0 pe-4">
                <a href="{% url 'website:index' %}" class="nav-item nav-link">صفحه اصلی</a>
                <a href="{% url 'website:about' %}" class="nav-item nav-link">درباره ما</a>
                <a href="{% url 'website:menu' %}" class="nav-item nav-link active">منوی غذا</a>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'account_logout' %}" class="nav-item nav-link">خروج از حساب کاربری</a>
                    <a href="{% url 'profile' %}" class="nav-item nav-link">پروفایل کاربری</a>
                {% else %}
                    <a href="{% url 'website:login' %}" class="nav-item nav-link">ورود / ثبت نام</a>
                {% endif %}
                <a href="{% url 'website:order_details2' %}" class="nav-item nav-link">جزئیات خرید</a>
            </div>
        </div>
    </nav>
</div>

<div class="container-xxl py-5 bg-dark hero-header mb-5">
    <div class="container text-center my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown"> منوی غذا</h1>
    </div>
</div>

{% include 'menu_content.html' %}

{% endblock %}

templates/order_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Navbar -->
<div class="container-xxl position-relative p-0">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
        <a href="{% url 'website:index' %}" class="navbar-brand p-0">
            <h1 style="color: whitesmoke;"><i class="text-primary m-0">紅龍 </i>اژدهای سرخ</h1>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="fa fa-bars"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0 pe-4">
                <a href="{% url 'website:index' %}" class="nav-item nav-link">صفحه اصلی</a>
                <a href="{% url 'website:about' %}" class="nav-item nav-link">درباره ما</a>
                <a href="{% url 'website:menu' %}" class="nav-item nav-link ">منوی غذا </a>
                {% if request.user.is_authenticated %}

                <a href="{% url 'account_logout' %}" class="nav-item nav-link">خروج از حساب کاربری</a>
                <a href="{% url 'profile' %}" class="nav-item nav-link">پروفایل کاربری</a>

                {% else %}
                <a href="{% url 'website:login' %}"  class="nav-item nav-link active">ورود / ثبت نام</a>

                {% endif %}
                <a href="{% url 'website:order_details2' %}"  class="nav-item nav-link">جزئیات خرید</a>
            </div>
        </div>
    </nav>
</div>

<div class="container-xxl py-5 bg-dark hero-header mb-5">
    <div class="container text-center my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">فاکتور خرید</h1>
    </div>
</div>

{% if is_order %}
    <h2 style="margin-right: 5%;"> از خرید شما متشکریم.</h2>
    <h2 style="margin-right: 5%;"> فاکتور خرید </h2>
    <h2 style="margin-right: 5%;">  {{ request.user.first_name }} {{ request.user.last_name }} :نام و نام خانوادگی</h2>
    <p style="margin-right: 5%;"> ایمیل: {{ request.user.email }}</p>
    <h4 style="margin-right: 5%;"> فاکتور</h4 >
    <p style="margin-right: 5%;"> تعداد محصولات: {{ order_count|floatformat:"0" }} عدد</p>
    <p style="margin-right: 5%;">مجموع کل: {{ order_price|floatformat:"0" }} تومان</p>
    <p style="margin-right: 5%;">نشانی: {{ request.user.home_address }}</p>
    <p style="margin-right: 5%;"> تخمین زمان آماده‌سازی: 20 دقیقه </p>
    <p style="margin-right: 5%;"> شماره خرید: </p>
{% else %}
    <h4 style="margin-right: 38%;"> شما هنوز خریدی را ثبت نکرده اید</h4>
{% endif %}

{% endblock %}

templates/test.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

  

</body>

</html>